### ISSUE TITLE
Build and install instructions

### ISSUE THREAD

**Issue by neilhwatson** [carlpett/bzfttr53rdutil#1]
I'm interested this project, but for none golang users better build and install instructions are required. Please consider adding them.

**Comment by carlpett** [comment]
@neilhwatson I'll fix that, thanks! Did you see that there are precompiled binaries available, though? You don't have to build it from source unless you need to change something.
If there is some os/arch combo I didn't build, please let me know and I'll upload those as well.

**Comment by carlpett** [comment]
@neilhwatson I updated the instructions now, are the new ones clearer?

**Comment by neilhwatson** [comment]
Sorry, I missed the binaries link. Instructions better to. Thanks.
